version: "3.8"
services:
  transcribe_tilern:
    build: .
    container_name: transcribe_tilern
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]   # можно убрать, если без GPU
